version: "3"

services:
  lb:
    image: haproxy
    ports:
      - "9090:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  microservice-test1:
    image: microservice-test
    environment:
      - APPID=1111
  microservice-test2:
    image: microservice-test
    environment:
      - APPID=2222
  microservice-test3:
    image: microservice-test
    environment:
      - APPID=3333
  microservice-test4:
    image: microservice-test
    environment:
      - APPID=4444
